server:
  port: 8003

# mybatis的整合
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml         # mybatis的配置文件信息
  type-aliases-package: cn.com.agree.springcloud.entities    # 所有实体类的的所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                        # mapper映射文件信息  这是一个数组
  
# springboot的整合
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5                                       # 数据库连接池的最小维持连接数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接获取的最大超时时间
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8003   #之定义服务名称信息
    prefer-ip-address: true      #访问路径可以显示IP
    
    
info:
  app.name: agree-microservicecloud
  company.name: www.agree.com.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$